settings:
  files:
    outputs:
      status: true
      path: ""
      name: logs/r.outputs.log
    logs:
      status: true
      path: ""
      name: logs/r.logs.log
    errors:
      status: true
      path: ""
      name: logs/r.errors.log
  legacy:
    force: true
    interval: 100ms
server:
  status: true
  open: true
  port: 5002
  host: localhost
schema:
- name: golog
  path: .
  commands:
      run:
        status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
